# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prob_c <- function(X, beta) {
    .Call(`_GroupHW_prob_c`, X, beta)
}

obj_c <- function(X, y, lambda, beta) {
    .Call(`_GroupHW_obj_c`, X, y, lambda, beta)
}

LRMultiClass_c <- function(X, y, numIter = 50L, eta = 0.1, lambda = 1, beta_init) {
    .Call(`_GroupHW_LRMultiClass_c`, X, y, numIter, eta, lambda, beta_init)
}

MyKmeans_c <- function(X, K, M, numIter = 100L) {
    .Call(`_GroupHW_MyKmeans_c`, X, K, M, numIter)
}

